CREATE TABLE `ejercicios` (
  `id` int(11) NOT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `nombre_ejercicio` varchar(100) NOT NULL,
  `grupo_muscular` varchar(50) NOT NULL,
  `tipo` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `ejercicios` (`id`, `id_usuario`, `nombre_ejercicio`, `grupo_muscular`, `tipo`) VALUES
(1, NULL, 'Press plano', 'Pecho', 'Fuerza'),
(2, NULL, 'Press plano mancuerna', 'Pecho', 'Fuerza'),
(3, NULL, 'Press plano mancuerna alternado', 'Pecho', 'Fuerza'),
(4, NULL, 'Press plano mancuerna agarre invertido', 'Pecho', 'Fuerza'),
(5, NULL, 'Press plano mancuerna trifásico', 'Pecho', 'Fuerza'),
(6, NULL, 'Press plano máquina', 'Pecho', 'Fuerza'),
(7, NULL, 'Press plano polea', 'Pecho', 'Fuerza'),
(8, NULL, 'Press plano disco', 'Pecho', 'Fuerza'),
(9, NULL, 'Press guillotina', 'Pecho', 'Fuerza'),
(10, NULL, 'Press inclinado', 'Pecho', 'Fuerza'),
(11, NULL, 'Press inclinado mancuerna', 'Pecho', 'Fuerza'),
(12, NULL, 'Press inclinado mancuerna alternado', 'Pecho', 'Fuerza'),
(13, NULL, 'Press inclinado mancuerna agarre invertido', 'Pecho', 'Fuerza'),
(14, NULL, 'Press inclinado mancuerna trifásico', 'Pecho', 'Fuerza'),
(15, NULL, 'Press inclinado máquina', 'Pecho', 'Fuerza'),
(16, NULL, 'Press inclinado polea', 'Pecho', 'Fuerza'),
(17, NULL, 'Press inclinado disco', 'Pecho', 'Fuerza'),
(18, NULL, 'Press declinado', 'Pecho', 'Fuerza'),
(19, NULL, 'Press declinado mancuerna', 'Pecho', 'Fuerza'),
(20, NULL, 'Press declinado mancuerna alternado', 'Pecho', 'Fuerza'),
(21, NULL, 'Press declinado mancuerna agarre invertido', 'Pecho', 'Fuerza'),
(22, NULL, 'Press declinado mancuerna trifásico', 'Pecho', 'Fuerza'),
(23, NULL, 'Vuelos mancuerna', 'Pecho', 'Fuerza'),
(24, NULL, 'Vuelos inclinado mancuerna', 'Pecho', 'Fuerza'),
(25, NULL, 'Vuelos declinado mancuerna', 'Pecho', 'Fuerza'),
(26, NULL, 'Vuelos máquina', 'Pecho', 'Fuerza'),
(27, NULL, 'Vuelos peso corporal', 'Pecho', 'Fuerza'),
(28, NULL, 'Vuelos polea inclinado', 'Pecho', 'Fuerza'),
(29, NULL, 'Vuelos polea declinado', 'Pecho', 'Fuerza'),
(30, NULL, 'Around the worlds', 'Pecho', 'Fuerza'),
(31, NULL, 'Press svend', 'Pecho', 'Fuerza'),
(32, NULL, 'Pullover pecho mancuerna', 'Pecho', 'Fuerza'),
(33, NULL, 'Pullover pecho barra', 'Pecho', 'Fuerza'),
(34, NULL, 'Fondos pecho paralelas', 'Pecho', 'Fuerza'),
(35, NULL, 'Pushups', 'Pecho', 'Fuerza'),
(36, NULL, 'Pushups diamante', 'Pecho', 'Fuerza'),
(37, NULL, 'Pushups archer', 'Pecho', 'Fuerza'),
(38, NULL, 'Pushups thumbs-up', 'Pecho', 'Fuerza'),
(39, NULL, 'Wipers isométricos', 'Pecho', 'Fuerza'),
(40, NULL, 'Remo shotgun', 'Espalda', 'Fuerza'),
(41, NULL, 'Remo mancuerna unipodal', 'Espalda', 'Fuerza'),
(42, NULL, 'Remo mancuerna banco inclinado', 'Espalda', 'Fuerza'),
(43, NULL, 'Remo barra parado', 'Espalda', 'Fuerza'),
(44, NULL, 'Remo polea sentado', 'Espalda', 'Fuerza'),
(45, NULL, 'Remo polea sentado unipodal', 'Espalda', 'Fuerza'),
(46, NULL, 'Remo máquina', 'Espalda', 'Fuerza'),
(47, NULL, 'Remo landmine', 'Espalda', 'Fuerza'),
(48, NULL, 'Remo invertido smith', 'Espalda', 'Fuerza'),
(49, NULL, 'Remo invertido trx', 'Espalda', 'Fuerza'),
(50, NULL, 'Muscleups', 'Espalda', 'Fuerza'),
(51, NULL, 'Pullups', 'Espalda', 'Fuerza'),
(52, NULL, 'Escapulario mancuerna banco inclinado', 'Espalda', 'Fuerza'),
(53, NULL, 'Escapulario mancuerna sobre rodilla', 'Espalda', 'Fuerza'),
(54, NULL, 'Escapulario máquina', 'Espalda', 'Fuerza'),
(55, NULL, 'Pullover lat mancuerna', 'Espalda', 'Fuerza'),
(56, NULL, 'Pullover lat barra', 'Espalda', 'Fuerza'),
(57, NULL, 'Chinups', 'Espalda', 'Fuerza'),
(58, NULL, 'Pullups asistidos', 'Espalda', 'Fuerza'),
(59, NULL, 'Chinups asistidos', 'Espalda', 'Fuerza'),
(60, NULL, 'Pulldown polea sentado ', 'Espalda', 'Fuerza'),
(61, NULL, 'Pulldown polea sentado agarre en v', 'Espalda', 'Fuerza'),
(62, NULL, 'Lat pulldown polea sentado', 'Espalda', 'Fuerza'),
(63, NULL, 'Pulldown polea parado', 'Espalda', 'Fuerza'),
(64, NULL, 'Pulldown polea parado lazo', 'Espalda', 'Fuerza'),
(65, NULL, 'Pulldown máquina', 'Espalda', 'Fuerza'),
(66, NULL, 'Lat pulldown máquina', 'Espalda', 'Fuerza'),
(67, NULL, 'Extensión de espalda libre', 'Espalda', 'Fuerza'),
(68, NULL, 'Extensión de espalda máquina', 'Espalda', 'Fuerza'),
(69, NULL, 'Supermans', 'Espalda', 'Fuerza'),
(70, NULL, 'Paracaídas', 'Espalda', 'Fuerza'),
(71, NULL, 'Plancha paracaídas', 'Espalda', 'Fuerza'),
(72, NULL, 'Good mornings sentado', 'Espalda', 'Fuerza'),
(73, NULL, 'Shrug smith', 'Trapecios', 'Fuerza'),
(74, NULL, 'Shrug smith invertido', 'Trapecios', 'Fuerza'),
(75, NULL, 'Shrug mancuerna', 'Trapecios', 'Fuerza'),
(76, NULL, 'Shrug barra', 'Trapecios', 'Fuerza'),
(77, NULL, 'Shrug polea', 'Trapecios', 'Fuerza'),
(78, NULL, 'Shrug polea lazo', 'Trapecios', 'Fuerza'),
(79, NULL, 'Shrug disco', 'Trapecios', 'Fuerza'),
(80, NULL, 'Upright row smith', 'Trapecios', 'Fuerza'),
(81, NULL, 'Upright row mancuerna', 'Trapecios', 'Fuerza'),
(82, NULL, 'Upright row barra', 'Trapecios', 'Fuerza'),
(83, NULL, 'Upright row polea', 'Trapecios', 'Fuerza'),
(84, NULL, 'Upright row polea lazo', 'Trapecios', 'Fuerza'),
(85, NULL, 'Upright row disco', 'Trapecios', 'Fuerza'),
(86, NULL, 'Elevaciones frontales disco para traps', 'Trapecios', 'Fuerza'),
(87, NULL, 'Press antigravedad mancuerna', 'Trapecios', 'Fuerza'),
(88, NULL, 'Press antigravedad barra', 'Trapecios', 'Fuerza'),
(89, NULL, 'Peso muerto ', 'Pierna', 'Fuerza'),
(90, NULL, 'Peso muerto mancuerna', 'Pierna', 'Fuerza'),
(91, NULL, 'Peso muerto sumo', 'Pierna', 'Fuerza'),
(92, NULL, 'Peso muerto sumo mancuerna', 'Pierna', 'Fuerza'),
(93, NULL, 'Curl femoral mancuerna', 'Pierna', 'Fuerza'),
(94, NULL, 'Curl femoral máquina sentado', 'Pierna', 'Fuerza'),
(95, NULL, 'Curl femoral máquina acostado', 'Pierna', 'Fuerza'),
(96, NULL, 'Press pierna máquina', 'Pierna', 'Fuerza'),
(97, NULL, 'Press pierna péndulo', 'Pierna', 'Fuerza'),
(98, NULL, 'Sentadilla hack', 'Pierna', 'Fuerza'),
(99, NULL, 'Estocada mancuerna', 'Pierna', 'Fuerza'),
(100, NULL, 'Estocada barra', 'Pierna', 'Fuerza'),
(101, NULL, 'Sentadilla barra libre', 'Pierna', 'Fuerza'),
(102, NULL, 'Sentadilla sumo mancuerna', 'Pierna', 'Fuerza'),
(103, NULL, 'Sentadilla sumo barra libre', 'Pierna', 'Fuerza'),
(104, NULL, 'Sentadilla mancuerna', 'Pierna', 'Fuerza'),
(105, NULL, 'Sentadilla smith', 'Pierna', 'Fuerza'),
(106, NULL, 'Sentadilla máquina', 'Pierna', 'Fuerza'),
(107, NULL, 'Saltos explosivos', 'Pierna', 'Fuerza'),
(108, NULL, 'Saltos en tijera', 'Pierna', 'Fuerza'),
(109, NULL, 'Extensiones de pierna máquina', 'Pierna', 'Fuerza'),
(110, NULL, 'Sentadilla alien', 'Pierna', 'Fuerza'),
(111, NULL, 'Sentadilla goblet', 'Pierna', 'Fuerza'),
(112, NULL, 'Sentadilla pistol', 'Pierna', 'Fuerza'),
(113, NULL, 'Sentadilla búlgara unipodal', 'Pierna', 'Fuerza'),
(114, NULL, 'Puente', 'Pierna', 'Fuerza'),
(115, NULL, 'Puente barra', 'Pierna', 'Fuerza'),
(116, NULL, 'Hip trust barra', 'Pierna', 'Fuerza'),
(117, NULL, 'Extensión cadera polea', 'Pierna', 'Fuerza'),
(118, NULL, 'Puente unipodal', 'Pierna', 'Fuerza'),
(119, NULL, 'Kickback gluteo colchoneta', 'Pierna', 'Fuerza'),
(120, NULL, 'Kickback gluteo polea', 'Pierna', 'Fuerza'),
(121, NULL, 'Pull throughs polea', 'Pierna', 'Fuerza'),
(122, NULL, 'Aducción cadera máquina', 'Pierna', 'Fuerza'),
(123, NULL, 'Groiners', 'Pierna', 'Fuerza'),
(124, NULL, 'Groiners unipodal', 'Pierna', 'Fuerza'),
(125, NULL, 'Lateral hop', 'Pierna', 'Fuerza'),
(126, NULL, 'Abducción cadera polea', 'Pierna', 'Fuerza'),
(127, NULL, 'Hidrante de fuego', 'Pierna', 'Fuerza'),
(128, NULL, 'Clam', 'Pierna', 'Fuerza'),
(129, NULL, 'Clam banda de resistencia', 'Pierna', 'Fuerza'),
(130, NULL, 'Monster walk', 'Pierna', 'Fuerza'),
(131, NULL, 'Abducción cadera máquina', 'Pierna', 'Fuerza'),
(132, NULL, 'Elevación pantorrilla ', 'Pierna', 'Fuerza'),
(133, NULL, 'Elevación pantorrilla unipodal', 'Pierna', 'Fuerza'),
(134, NULL, 'Elevación pantorrilla máquina sentado', 'Pierna', 'Fuerza'),
(135, NULL, 'Press pantorilla en prensa', 'Pierna', 'Fuerza'),
(136, NULL, 'Press pantorilla smith', 'Pierna', 'Fuerza'),
(137, NULL, 'Frog situps', 'Abdomen', 'Fuerza'),
(138, NULL, 'Situps 3/4', 'Abdomen', 'Fuerza'),
(139, NULL, 'Elevaciones de pierna', 'Abdomen', 'Fuerza'),
(140, NULL, 'Elevaciones de pierna balón', 'Abdomen', 'Fuerza'),
(141, NULL, 'Elevaciones de pierna colgando', 'Abdomen', 'Fuerza'),
(142, NULL, 'Elevaciones around the world', 'Abdomen', 'Fuerza'),
(143, NULL, 'Plancha', 'Abdomen', 'Fuerza'),
(144, NULL, 'Plancha con disco', 'Abdomen', 'Fuerza'),
(145, NULL, 'Plancha con una pierna', 'Abdomen', 'Fuerza'),
(146, NULL, 'Plancha sierra', 'Abdomen', 'Fuerza'),
(147, NULL, 'Plancha spiderman', 'Abdomen', 'Fuerza'),
(148, NULL, 'Escalador', 'Abdomen', 'Fuerza'),
(149, NULL, 'Burpees', 'Abdomen', 'Fuerza'),
(150, NULL, 'Crunch inverso', 'Abdomen', 'Fuerza'),
(151, NULL, 'Crunch inverso declinado', 'Abdomen', 'Fuerza'),
(152, NULL, 'Cocoons', 'Abdomen', 'Fuerza'),
(153, NULL, 'Crunch declinado', 'Abdomen', 'Fuerza'),
(154, NULL, 'Crunch de codo a rodilla', 'Abdomen', 'Fuerza'),
(155, NULL, 'Crunch suitcase', 'Abdomen', 'Fuerza'),
(156, NULL, 'Giro ruso con disco', 'Abdomen', 'Fuerza'),
(157, NULL, 'Rollout de abdomen', 'Abdomen', 'Fuerza'),
(158, NULL, 'Roullout de abdomen parado', 'Abdomen', 'Fuerza'),
(159, NULL, 'Pull-in con balón', 'Abdomen', 'Fuerza'),
(160, NULL, 'Otis-up', 'Abdomen', 'Fuerza'),
(161, NULL, 'Crunches', 'Abdomen', 'Fuerza'),
(162, NULL, 'V-ups', 'Abdomen', 'Fuerza'),
(163, NULL, 'Crunch oblicuos declinado', 'Abdomen', 'Fuerza'),
(164, NULL, 'Pull-in de pierna en borde de banco', 'Abdomen', 'Fuerza'),
(165, NULL, 'Butt-ups', 'Abdomen', 'Fuerza'),
(166, NULL, 'Tocada de tobillos alternada', 'Abdomen', 'Fuerza'),
(167, NULL, 'Puente lateral', 'Abdomen', 'Fuerza'),
(168, NULL, 'Crunch de oblicuos colchoneta', 'Abdomen', 'Fuerza'),
(169, NULL, 'Toe touchers', 'Abdomen', 'Fuerza'),
(170, NULL, 'Full moon', 'Abdomen', 'Fuerza'),
(171, NULL, 'Patada lateral', 'Abdomen', 'Fuerza'),
(172, NULL, 'Windmill', 'Abdomen', 'Fuerza'),
(173, NULL, 'Curl barra', 'Bíceps', 'Fuerza'),
(174, NULL, 'Curl mancuerna', 'Bíceps', 'Fuerza'),
(175, NULL, 'Curl mancuerna unipodal', 'Bíceps', 'Fuerza'),
(176, NULL, 'Curl zottman', 'Bíceps', 'Fuerza'),
(177, NULL, 'Curl martillo mancuerna', 'Bíceps', 'Fuerza'),
(178, NULL, 'Curl martillo barra suisa', 'Bíceps', 'Fuerza'),
(179, NULL, 'Curl invertido mancuerna', 'Bíceps', 'Fuerza'),
(180, NULL, 'Curl invertido barra z', 'Bíceps', 'Fuerza'),
(181, NULL, 'Curl spider', 'Bíceps', 'Fuerza'),
(182, NULL, 'Curl concentrado unipodal', 'Bíceps', 'Fuerza'),
(183, NULL, 'Predicador barra', 'Bíceps', 'Fuerza'),
(184, NULL, 'Predicador mancuerna unipodal', 'Bíceps', 'Fuerza'),
(185, NULL, 'Predicador máquina', 'Bíceps', 'Fuerza'),
(186, NULL, 'Curl polea', 'Bíceps', 'Fuerza'),
(187, NULL, 'Curl polea lazo', 'Bíceps', 'Fuerza'),
(188, NULL, 'De curl a press hombro', 'Bíceps', 'Fuerza'),
(189, NULL, 'Curl trifásico', 'Bíceps', 'Fuerza'),
(190, NULL, 'Curl ancho barra', 'Bíceps', 'Fuerza'),
(191, NULL, 'Curl estrecho barra', 'Bíceps', 'Fuerza'),
(192, NULL, 'Curl mancuerna sentado inclinado', 'Bíceps', 'Fuerza'),
(193, NULL, 'Curl polea por encima de la cabeza', 'Bíceps', 'Fuerza'),
(194, NULL, 'Curl polea acostado', 'Bíceps', 'Fuerza'),
(195, NULL, 'Patada doble ', 'Tríceps', 'Fuerza'),
(196, NULL, 'Extensión tríceps mancuerna acostado', 'Tríceps', 'Fuerza'),
(197, NULL, 'Extensión tríceps mancuerna sentado', 'Tríceps', 'Fuerza'),
(198, NULL, 'Skullcrusher', 'Tríceps', 'Fuerza'),
(199, NULL, 'Tate press ', 'Tríceps', 'Fuerza'),
(200, NULL, 'Press estrecho', 'Tríceps', 'Fuerza'),
(201, NULL, 'Body ups', 'Tríceps', 'Fuerza'),
(202, NULL, 'Push ups estrechos', 'Tríceps', 'Fuerza'),
(203, NULL, 'Extensión tríceps máquina', 'Tríceps', 'Fuerza'),
(204, NULL, 'Extensión tríceps mancuerna unipodal sentado', 'Tríceps', 'Fuerza'),
(205, NULL, 'Fondos tríceps paralelas', 'Tríceps', 'Fuerza'),
(206, NULL, 'Fondos tríceps máquina sentado', 'Tríceps', 'Fuerza'),
(207, NULL, 'Fondos tríceps máquina asistencia', 'Tríceps', 'Fuerza'),
(208, NULL, 'Extensión tríceps polea', 'Tríceps', 'Fuerza'),
(209, NULL, 'Extensión tríceps polea unipodal', 'Tríceps', 'Fuerza'),
(210, NULL, 'Extensión tríceps polea unipodal lazo', 'Tríceps', 'Fuerza'),
(211, NULL, 'Extensión tríceps polea lazo', 'Tríceps', 'Fuerza'),
(212, NULL, 'Extensión tríceps suspendido', 'Tríceps', 'Fuerza'),
(213, NULL, 'Press militar mancuerna parado', 'Hombro', 'Fuerza'),
(214, NULL, 'Press militar mancuerna sentado', 'Hombro', 'Fuerza'),
(215, NULL, 'Press militar barra parado', 'Hombro', 'Fuerza'),
(216, NULL, 'Press militar barra sentado', 'Hombro', 'Fuerza'),
(217, NULL, 'Press militar máquina ', 'Hombro', 'Fuerza'),
(218, NULL, 'Press hombro mancuerna parado', 'Hombro', 'Fuerza'),
(219, NULL, 'Press hombro mancuerna sentado', 'Hombro', 'Fuerza'),
(220, NULL, 'Press hombro mancuerna trifásico', 'Hombro', 'Fuerza'),
(221, NULL, 'Press hombro mancuerna sentado alternado', 'Hombro', 'Fuerza'),
(222, NULL, 'Press hombro barra parado', 'Hombro', 'Fuerza'),
(223, NULL, 'Press hombro barra sentado', 'Hombro', 'Fuerza'),
(224, NULL, 'Press hombro máquina', 'Hombro', 'Fuerza'),
(225, NULL, 'Press arnold', 'Hombro', 'Fuerza'),
(226, NULL, 'Press cubano', 'Hombro', 'Fuerza'),
(227, NULL, 'Elevaciones laterales mancuerna', 'Hombro', 'Fuerza'),
(228, NULL, 'Elevaciones laterales mancuerna unipodal', 'Hombro', 'Fuerza'),
(229, NULL, 'Elevaciones laterales polea unipodal', 'Hombro', 'Fuerza'),
(230, NULL, 'Elevaciones laterales mancuerna banco inclinado', 'Hombro', 'Fuerza'),
(231, NULL, 'Elevaciones laterales máquina', 'Hombro', 'Fuerza'),
(232, NULL, 'Elevaciones frontales disco', 'Hombro', 'Fuerza'),
(233, NULL, 'Elevaciones frontales mancuerna', 'Hombro', 'Fuerza'),
(234, NULL, 'Elevaciones frontales barra', 'Hombro', 'Fuerza'),
(235, NULL, 'Elevaciones frontales polea', 'Hombro', 'Fuerza'),
(236, NULL, 'Elevaciones frontales barra banco inclinado', 'Hombro', 'Fuerza'),
(237, NULL, 'Car driver', 'Hombro', 'Fuerza'),
(238, NULL, 'Rotación hombro disco', 'Hombro', 'Fuerza'),
(239, NULL, 'Elevaciones de lateral a frontal', 'Hombro', 'Fuerza'),
(240, NULL, 'Rotación externa polea unipodal', 'Hombro', 'Fuerza'),
(241, NULL, 'Rotación interna polea unipodal', 'Hombro', 'Fuerza');

CREATE TABLE `entrenamientos` (
  `id` int(11) NOT NULL,
  `id_usuario` int(11) NOT NULL,
  `fecha` date NOT NULL,
  `nombre_entrenamiento` varchar(100) NOT NULL,
  `notas` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `series` (
  `id` int(11) NOT NULL,
  `id_entrenamiento` int(11) NOT NULL,
  `id_ejercicio` int(11) NOT NULL,
  `num_serie` int(11) NOT NULL,
  `descanso_seg` int(11) DEFAULT NULL,
  `repeticiones` int(11) NOT NULL,
  `peso_kg` decimal(5,2) DEFAULT NULL,
  `notas` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nombre_usuario` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `rol` enum('usuario','admin') NOT NULL DEFAULT 'usuario',
  `estado` enum('activo','pendiente') NOT NULL DEFAULT 'pendiente'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `usuarios` (`id`, `nombre_usuario`, `email`, `password_hash`, `rol`, `estado`) VALUES
(1, 'Cristian', 'cristian@myworkoutlog.com', '$2y$10$sj31NkLN4/ZotjOk1A5Z0.IHk6trLjLTMsgRd.gP5n56okfYx1ek.', 'admin', 'activo'),
(2, 'Maria', 'maria@myworkoutlog.com', '$2y$10$sj31NkLN4/ZotjOk1A5Z0.IHk6trLjLTMsgRd.gP5n56okfYx1ek.', 'usuario', 'activo');

ALTER TABLE `ejercicios`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_ejercicios_usuarios` (`id_usuario`);

ALTER TABLE `entrenamientos`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_entrenamientos_usuarios` (`id_usuario`);

ALTER TABLE `series`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_series_entrenamientos` (`id_entrenamiento`),
  ADD KEY `fk_series_ejercicios` (`id_ejercicio`);

ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

ALTER TABLE `ejercicios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=248;

ALTER TABLE `entrenamientos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=74;

ALTER TABLE `series`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=479;

ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

ALTER TABLE `ejercicios`
  ADD CONSTRAINT `fk_ejercicios_usuarios` FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE;

ALTER TABLE `entrenamientos`
  ADD CONSTRAINT `fk_entrenamientos_usuarios` FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE;

ALTER TABLE `series`
  ADD CONSTRAINT `fk_series_ejercicios` FOREIGN KEY (`id_ejercicio`) REFERENCES `ejercicios` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_series_entrenamientos` FOREIGN KEY (`id_entrenamiento`) REFERENCES `entrenamientos` (`id`) ON DELETE CASCADE;
COMMIT;
